### ISSUE TITLE
Function overloading

### ISSUE THREAD

**Issue by shd101wyy** [runtimeverification/solidity#164]
For the following solidity code 

```solidity
pragma solidity ^0.4.7;

contract Test {
    event print(bool passed, string message);
    function equal(uint x, uint y, string message) public {
        bool result = (x == y);
        emit print(result, message);
    }
    
    function equal(int x, int y, string message) public {
        bool result = (x == y);
        emit print(result, message);
    }
    
    function equal(bool x, bool y, string message) public {
        bool result = (x == y);
        emit print(result, message);
    }
    
    
    function test() public {
        equal(uint(4), uint(4), "Hi");
    }
}
```

When I try to compile that code with `isolc` command, I get the following error:

```
overloading.sol:22:9: Error: No unique declaration found after argument-dependent lookup.
        equal(uint(4), uint(4), "Hi");
        ^---^
```

But `solc` compiler just compiles that code without any problem.

If I remove  `function equal(int x, int y, string message)` function, then `isolc` could compile it.

Am I doing something wrong here? Thank you

**Comment by theo25** [comment]
The problem here is that in Solidity-to-IELE the conversion `uint -> int` is implicit, since there is no loss of information, but in Solidity-to-EVM (and Solidity-to-IELE for that matter) the conversion `uin256 -> int256` is *not* implicit because there is potential loss of information: the signed datatype uses 1 bit for sign hence has 1 bit less available to represent positive numbers. As a result `solc` finds only one compatible callee for the call to `equal` in line 22, because in `solc`, `uint` and `int` are syntactic sugar for `uint256` and `int256` and therefore there is no implicit conversion that would add another compatible callee. In `isolc` on the other hand there are two compatible callees.

To me, this is working as intended for our unbounded datatypes. Do you agree @dwightguth?

**Comment by theo25** [comment]
FYI, `isolc` compiles the program successfully if you replace `uint` with `uint64` and `int` with `int64` everywhere. However it issues the same error as in the OP, if you replace `uint` with `uint64` and `int` with `int128` everywhere.

**Comment by shd101wyy** [comment]
Thank you for the explanation! I think i will modify the demo of the
solidity code in remix ide then.
